version: '3'

services:
  nodejs:
    container_name: inspiring_feynman
    image: lucassanches/dockernode
    build:
      context: .
      dockerfile: ./Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./home/usr/app
      